import { Player, Team, Match, ClubData } from './dataManagementService';

// Enhanced mock players with more realistic data and statistics
export const mockPlayers: Player[] = [
  { 
    id: '1', 
    name: 'Lionel Messi', 
    position: 'RW', 
    jersey_number: 10, 
    age: 36, 
    nationality: 'Argentina',
    photo_url: 'https://example.com/messi.jpg',
    height: 170,
    weight: 72,
    preferred_foot: 'left',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 35,
    assists: 28,
    matches: 42,
    rating: 9.2,
    passAccuracy: 89,
    form: 'excellent',
    fitnessLevel: 95,
    injuryRisk: 15,
    potentialGrowth: 5,
    mentalState: 'Focused',
    trainingLoad: 80,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '2', 
    name: 'Cristiano Ronaldo', 
    position: 'ST', 
    jersey_number: 7, 
    age: 38, 
    nationality: 'Portugal',
    photo_url: 'https://example.com/ronaldo.jpg',
    height: 187,
    weight: 83,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 32,
    assists: 12,
    matches: 38,
    rating: 8.9,
    passAccuracy: 82,
    form: 'excellent',
    fitnessLevel: 92,
    injuryRisk: 25,
    potentialGrowth: 3,
    mentalState: 'Determined',
    trainingLoad: 85,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '3', 
    name: 'Neymar Jr', 
    position: 'LW', 
    jersey_number: 11, 
    age: 31, 
    nationality: 'Brazil',
    photo_url: 'https://example.com/neymar.jpg',
    height: 175,
    weight: 68,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 28,
    assists: 35,
    matches: 40,
    rating: 8.7,
    passAccuracy: 85,
    form: 'good',
    fitnessLevel: 88,
    injuryRisk: 40,
    potentialGrowth: 8,
    mentalState: 'Creative',
    trainingLoad: 75,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '4', 
    name: 'Kylian Mbappé', 
    position: 'ST', 
    jersey_number: 9, 
    age: 25, 
    nationality: 'France',
    photo_url: 'https://example.com/mbappe.jpg',
    height: 178,
    weight: 73,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 42,
    assists: 15,
    matches: 45,
    rating: 9.1,
    passAccuracy: 80,
    form: 'excellent',
    fitnessLevel: 96,
    injuryRisk: 10,
    potentialGrowth: 15,
    mentalState: 'Energetic',
    trainingLoad: 90,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '5', 
    name: 'Kevin De Bruyne', 
    position: 'CM', 
    jersey_number: 17, 
    age: 32, 
    nationality: 'Belgium',
    photo_url: 'https://example.com/debruyne.jpg',
    height: 181,
    weight: 68,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 12,
    assists: 48,
    matches: 44,
    rating: 8.8,
    passAccuracy: 92,
    form: 'excellent',
    fitnessLevel: 90,
    injuryRisk: 20,
    potentialGrowth: 2,
    mentalState: 'Strategic',
    trainingLoad: 82,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '6', 
    name: 'Virgil van Dijk', 
    position: 'CB', 
    jersey_number: 4, 
    age: 32, 
    nationality: 'Netherlands',
    photo_url: 'https://example.com/vandijk.jpg',
    height: 193,
    weight: 92,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 5,
    assists: 3,
    matches: 39,
    rating: 8.5,
    passAccuracy: 88,
    form: 'good',
    fitnessLevel: 87,
    injuryRisk: 18,
    potentialGrowth: 1,
    mentalState: 'Leadership',
    trainingLoad: 78,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '7', 
    name: 'Thibaut Courtois', 
    position: 'GK', 
    jersey_number: 1, 
    age: 31, 
    nationality: 'Belgium',
    photo_url: 'https://example.com/courtois.jpg',
    height: 199,
    weight: 96,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 0,
    assists: 1,
    matches: 37,
    rating: 8.6,
    passAccuracy: 75,
    form: 'good',
    fitnessLevel: 91,
    injuryRisk: 22,
    potentialGrowth: 0,
    mentalState: 'Confident',
    trainingLoad: 70,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '8', 
    name: 'Erling Haaland', 
    position: 'ST', 
    jersey_number: 9, 
    age: 23, 
    nationality: 'Norway',
    photo_url: 'https://example.com/haaland.jpg',
    height: 195,
    weight: 91,
    preferred_foot: 'left',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 38,
    assists: 8,
    matches: 41,
    rating: 9.0,
    passAccuracy: 78,
    form: 'excellent',
    fitnessLevel: 94,
    injuryRisk: 12,
    potentialGrowth: 20,
    mentalState: 'Relentless',
    trainingLoad: 88,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '9', 
    name: 'Mohamed Salah', 
    position: 'RW', 
    jersey_number: 11, 
    age: 31, 
    nationality: 'Egypt',
    photo_url: 'https://example.com/salah.jpg',
    height: 175,
    weight: 71,
    preferred_foot: 'left',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 29,
    assists: 22,
    matches: 39,
    rating: 8.7,
    passAccuracy: 83,
    form: 'good',
    fitnessLevel: 89,
    injuryRisk: 28,
    potentialGrowth: 4,
    mentalState: 'Clinical',
    trainingLoad: 83,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '10', 
    name: 'Luka Modrić', 
    position: 'CM', 
    jersey_number: 10, 
    age: 38, 
    nationality: 'Croatia',
    photo_url: 'https://example.com/modric.jpg',
    height: 172,
    weight: 66,
    preferred_foot: 'both',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 6,
    assists: 25,
    matches: 36,
    rating: 8.4,
    passAccuracy: 91,
    form: 'good',
    fitnessLevel: 85,
    injuryRisk: 30,
    potentialGrowth: 1,
    mentalState: 'Experienced',
    trainingLoad: 75,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '11', 
    name: 'Sergio Ramos', 
    position: 'CB', 
    jersey_number: 4, 
    age: 37, 
    nationality: 'Spain',
    photo_url: 'https://example.com/ramos.jpg',
    height: 184,
    weight: 82,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 3,
    assists: 2,
    matches: 34,
    rating: 8.2,
    passAccuracy: 85,
    form: 'good',
    fitnessLevel: 83,
    injuryRisk: 35,
    potentialGrowth: 0,
    mentalState: 'Leadership',
    trainingLoad: 72,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  { 
    id: '12', 
    name: 'Karim Benzema', 
    position: 'ST', 
    jersey_number: 9, 
    age: 36, 
    nationality: 'France',
    photo_url: 'https://example.com/benzema.jpg',
    height: 185,
    weight: 81,
    preferred_foot: 'right',
    status: 'active',
    team_id: '1',
    user_id: 'user1',
    goals: 22,
    assists: 18,
    matches: 35,
    rating: 8.6,
    passAccuracy: 84,
    form: 'good',
    fitnessLevel: 86,
    injuryRisk: 22,
    potentialGrowth: 2,
    mentalState: 'Clinical',
    trainingLoad: 77,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const mockTeam: Team = {
  id: '1',
  name: 'FC Barcelona',
  sport: 'Football',
  description: 'Professional football club based in Barcelona, Spain',
  logo_url: 'https://example.com/barcelona.png',
  formation: '4-3-3',
  owner_id: 'user1',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString()
};

// Enhanced mock matches with more realistic data and completed matches
export const mockMatches: Match[] = [
  {
    id: '1',
    team_id: '1',
    opponent_name: 'Real Madrid',
    match_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
    location: 'Camp Nou',
    match_type: 'League',
    home_score: 4,
    away_score: 3,
    is_home: true,
    status: 'completed',
    formation: '4-3-3',
    notes: 'El Clásico - Thrilling victory with late winner',
    weather: 'Sunny',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '2',
    team_id: '1',
    opponent_name: 'Bayern Munich',
    match_date: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(), // 25 days ago
    location: 'Allianz Arena',
    match_type: 'Champions League',
    home_score: 2,
    away_score: 3,
    is_home: false,
    status: 'completed',
    formation: '4-3-3',
    notes: 'Champions League group stage match',
    weather: 'Cloudy',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '3',
    team_id: '1',
    opponent_name: 'Manchester City',
    match_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), // 20 days ago
    location: 'Camp Nou',
    match_type: 'Friendly',
    home_score: 1,
    away_score: 1,
    is_home: true,
    status: 'completed',
    formation: '4-3-3',
    notes: 'Pre-season friendly match',
    weather: 'Rainy',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '4',
    team_id: '1',
    opponent_name: 'Paris Saint-Germain',
    match_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), // 15 days ago
    location: 'Parc des Princes',
    match_type: 'Champions League',
    home_score: 3,
    away_score: 2,
    is_home: false,
    status: 'completed',
    formation: '4-3-3',
    notes: 'Champions League knockout stage',
    weather: 'Clear',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '5',
    team_id: '1',
    opponent_name: 'Atlético Madrid',
    match_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
    location: 'Camp Nou',
    match_type: 'League',
    home_score: 2,
    away_score: 0,
    is_home: true,
    status: 'completed',
    formation: '4-3-3',
    notes: 'League match with clean sheet',
    weather: 'Sunny',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '6',
    team_id: '1',
    opponent_name: 'Liverpool',
    match_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    location: 'Anfield',
    match_type: 'Friendly',
    home_score: 0,
    away_score: 2,
    is_home: false,
    status: 'completed',
    formation: '4-3-3',
    notes: 'Friendly match against Premier League side',
    weather: 'Overcast',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '7',
    team_id: '1',
    opponent_name: 'Juventus',
    match_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    location: 'Camp Nou',
    match_type: 'Friendly',
    home_score: 0,
    away_score: 0,
    is_home: true,
    status: 'scheduled',
    formation: '4-3-3',
    notes: 'Friendly match against Serie A champions',
    weather: 'Clear',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '8',
    team_id: '1',
    opponent_name: 'Chelsea',
    match_date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(), // 9 days from now
    location: 'Stamford Bridge',
    match_type: 'Champions League',
    home_score: 0,
    away_score: 0,
    is_home: false,
    status: 'scheduled',
    formation: '4-3-3',
    notes: 'Champions League quarter-final',
    weather: 'Cloudy',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '9',
    team_id: '1',
    opponent_name: 'Sevilla',
    match_date: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(), // 16 days from now
    location: 'Camp Nou',
    match_type: 'League',
    home_score: 0,
    away_score: 0,
    is_home: true,
    status: 'scheduled',
    formation: '4-3-3',
    notes: 'League match against local rivals',
    weather: 'Sunny',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '10',
    team_id: '1',
    opponent_name: 'Borussia Dortmund',
    match_date: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(), // 23 days from now
    location: 'Signal Iduna Park',
    match_type: 'Friendly',
    home_score: 0,
    away_score: 0,
    is_home: false,
    status: 'scheduled',
    formation: '4-3-3',
    notes: 'Pre-season friendly in Germany',
    weather: 'Clear',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '11',
    team_id: '1',
    opponent_name: 'AC Milan',
    match_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days from now
    location: 'Camp Nou',
    match_type: 'Champions League',
    home_score: 0,
    away_score: 0,
    is_home: true,
    status: 'scheduled',
    formation: '4-3-3',
    notes: 'Champions League semi-final',
    weather: 'Clear',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '12',
    team_id: '1',
    opponent_name: 'Arsenal',
    match_date: new Date(Date.now() + 37 * 24 * 60 * 60 * 1000).toISOString(), // 37 days from now
    location: 'Emirates Stadium',
    match_type: 'Friendly',
    home_score: 0,
    away_score: 0,
    is_home: false,
    status: 'scheduled',
    formation: '4-3-3',
    notes: 'Friendly match against Premier League side',
    weather: 'Overcast',
    user_id: 'user1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const mockClubData: ClubData = {
  id: '1',
  name: 'FC Barcelona',
  founded: 1899,
  stadium: 'Camp Nou',
  capacity: 99354,
  address: 'C. d\'Aristides Maillol, 12, 08028 Barcelona, Spain',
  phone: '+34 934 96 96 96',
  email: 'info@fcbarcelona.com',
  budget: 1200000000,
  trophies: 156,
  notes: 'One of the most successful football clubs in the world'
};

export const mockAttendanceData = [
  {
    id: '1',
    playerId: '1',
    playerName: 'Lionel Messi',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '2',
    playerId: '2',
    playerName: 'Cristiano Ronaldo',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '3',
    playerId: '3',
    playerName: 'Neymar Jr',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'absent' as const,
    notes: 'Injury - hamstring strain'
  },
  {
    id: '4',
    playerId: '4',
    playerName: 'Kylian Mbappé',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '5',
    playerId: '5',
    playerName: 'Kevin De Bruyne',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '6',
    playerId: '6',
    playerName: 'Virgil van Dijk',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '7',
    playerId: '7',
    playerName: 'Thibaut Courtois',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '8',
    playerId: '8',
    playerName: 'Erling Haaland',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '9',
    playerId: '9',
    playerName: 'Mohamed Salah',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '10',
    playerId: '10',
    playerName: 'Luka Modrić',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '11',
    playerId: '11',
    playerName: 'Sergio Ramos',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '12',
    playerId: '12',
    playerName: 'Karim Benzema',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '13',
    playerId: '1',
    playerName: 'Lionel Messi',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '14',
    playerId: '2',
    playerName: 'Cristiano Ronaldo',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  },
  {
    id: '15',
    playerId: '3',
    playerName: 'Neymar Jr',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Recovered from injury'
  },
  {
    id: '16',
    playerId: '4',
    playerName: 'Kylian Mbappé',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'present' as const,
    notes: 'Full training session'
  }
];

// Function to get all mock data
export const getAllMockData = () => ({
  players: mockPlayers,
  team: mockTeam,
  matches: mockMatches,
  clubData: mockClubData,
  attendance: mockAttendanceData
});

// Function to get players for a specific team
export const getMockPlayersForTeam = (teamId?: string): Player[] => {
  if (!teamId) return mockPlayers;
  return mockPlayers.filter(player => player.team_id === teamId);
};

// Function to get a specific player by ID
export const getMockPlayerById = (id: string): Player | undefined => {
  return mockPlayers.find(player => player.id === id);
};

// Function to get matches for a specific team
export const getMockMatchesForTeam = (teamId?: string): Match[] => {
  if (!teamId) return mockMatches;
  return mockMatches.filter(match => match.team_id === teamId);
};